import { BaseLlmProvider } from './base';
import { AiGenerationRequest, AiGenerationResponse, LlmProviderType } from '../types';

export class DeepSeekProvider extends BaseLlmProvider {
  protected providerName: LlmProviderType = 'deepseek';
  protected defaultModel = 'deepseek-chat';

  async generate(request: AiGenerationRequest): Promise<AiGenerationResponse> {
    const start = Date.now();
    
    // Simulate real network call to DeepSeek API
    await this.simulateNetworkLatency(800); // DeepSeek is typically faster

    const latencyMs = Date.now() - start;

    return {
      content: `This is a highly analytical and structured campaign copy based on: "${request.prompt}".\n\n1. **Pain Point Analysis**: Most developers struggle with setting up authentication and databases.\n2. **Value Proposition**: A production-ready boilerplate saves 100+ hours of setup time.\n3. **Actionable Step**: Clone the repository and run 'npm run dev'.\n\n(Generated by DeepSeek ${this.defaultModel})`,
      provider: this.providerName,
      model: this.defaultModel,
      latencyMs,
    };
  }
}
