import { BaseLlmProvider } from './base';
import { AiGenerationRequest, AiGenerationResponse, LlmProviderType } from '../types';

export class OpenAiProvider extends BaseLlmProvider {
  protected providerName: LlmProviderType = 'openai';
  protected defaultModel = 'gpt-4o';

  async generate(request: AiGenerationRequest): Promise<AiGenerationResponse> {
    const start = Date.now();
    
    // Simulate real network call to OpenAI API
    // e.g. await openai.chat.completions.create({ model: this.defaultModel, messages: [...] })
    await this.simulateNetworkLatency(1200);

    // Randomly fail sometimes to demonstrate fallback routing in action
    if (Math.random() < 0.15) {
      throw new Error(`[OpenAI Error] Connection timeout to api.openai.com`);
    }

    const latencyMs = Date.now() - start;

    return {
      content: `Here is an engaging and conversion-optimized ad copy for your campaign based on: "${request.prompt}".\n\n🎯 **Hook**: Stop wasting money on inefficient marketing!\n💡 **Solution**: Discover how our Next.js SaaS Starter can 10x your speed to market.\n🚀 **CTA**: Start your free trial today!\n\n(Generated by OpenAI ${this.defaultModel})`,
      provider: this.providerName,
      model: this.defaultModel,
      latencyMs,
    };
  }
}
